My_Mobile_Apps = ['Airtel',
'Albums',
'Authenticator',
'Calculator',
'Calender',
'Camera',
'Chrome',
'Clock',
'Compass',
'Contacts',
'Drive',
'Edge',
'File Manager',
'gmail',
'gpay',
'i manager',
'maps',
'microsoft swiftkey keyboard',
'music',
'my business',
'notes',
'onenotes',
'outlook',
'phone',
'play store',
'recorder',
'settings',
'teams',
'to do',
'video',
'vivo cloud',
'weather',
'whatsapp',
'your phone',
'youtube',
'razorpay payroll']

My_Mobile_Apps.sort()
for i in range (len(My_Mobile_Apps)):
        print(My_Mobile_Apps[i],end =', ')